sudo: false
language: python

matrix:
  fast_finish: true
  include:
    - python: 2.7
      env: TOXENV=py27
    - python: 3.6
      env: TOXENV=py36
    - python: 3.7
      # from https://github.com/travis-ci/travis-ci/issues/9815#issuecomment-401756442
      dist: xenial
      env: TOXENV=py37
      sudo: true
install: python -mpip install tox-travis
script: tox

# encrpyt channel name to get around issue
# https://github.com/travis-ci/travis-ci/issues/1094
notifications:
  irc:
    channels:
      # encrpyted string was "irc.mozilla.org#taskcluster-bots"
      - secure: "I8h0AP0UKI2TaETVComWxWFGceaUgYNC4xlVTuDhsAteFUUYNL/ZnJqtKOGKxAem7kjngWYMhZyLJSfgXr5ev9HEkCansLh11UVHkytx/nlmJdcL0peMRFh1pQCVTKWSMywU/wbJZ4EgjZYMfSAcSHze/b5WqqQPP85YvbLb7dE="
    on_success: change
    on_failure: always
    template:
      - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}"
      - "Change view : %{compare_url}"
      - "Build details : %{build_url}"
      - "Commit message : %{commit_message}"
