language: python
python:
  - 2.7
  - pypy

env:
  NO_TESTS_OVER_WIRE=1

# command to install dependencies
install:
  - pip install virtualenv
  - make dev-env

# command to run tests
script:
  - make test
