apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: ${projectName}-${lowercase(procName)}
  labels: {$eval: labels}
spec:
  # TC crontasks assume they are not running concurrently
  concurrencyPolicy: Forbid
  schedule: ${schedule}
  jobTemplate:
    metadata:
      labels: {$eval: labels}
    spec:
      template:
        metadata:
          labels: {$eval: labels}
        spec:
          # On failure, just fail and wait for the next scheduled invocation
          restartPolicy: Never
          # terminate the pod one minute before the next job begins
          activeDeadlineSeconds: {$eval: 'deadlineSeconds - 60'}
          containers:
          - name: ${projectName}-${lowercase(procName)}
            image: '{{ .Values.dockerImage }}'
            imagePullPolicy: Always
            args: ['${serviceName}/${procName}']
            resources:
              requests:
                cpu: '{{ .Values.${configName}.procs.${configProcName}.cpu }}'
                memory: '{{ .Values.${configName}.procs.${configProcName}.memory }}'
            env:
              - name: TASKCLUSTER_ROOT_URL
                value: '{{ .Values.rootUrl }}'
              - name: USE_KUBERNETES_DNS_SERVICE_DISCOVERY
                value: '{{ .Values.useKubernetesDnsServiceDiscovery }}'
              - name: NODE_ENV
                value: 'production'
            envFrom:
              - secretRef:
                  name: ${projectName}
